spring:
  datasource:
    url: jdbc:mysql://kiha-beach/jwt_security
    username: ariuhzjyi
    password: D332J0UF4WG60747$
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
