spring:
  datasource:
    url: jdbc:mysql://kihabeachsqlserver.mysql.database.azure.com:3306/kihabeach
    username: kihaadmin
    password: meta@12345
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
